runtime: nodejs20

instance_class: B4
basic_scaling:
  max_instances: 1
  idle_timeout: 10m

env_variables:
  HOST: '0.0.0.0'
  NODE_ENV: 'production'
  DATABASE_HOST: '/cloudsql/strapi-cms-441915:us-central1:strapi'
  DATABASE_NAME: 'strapi'
  DATABASE_USERNAME: 'postgres'
  DATABASE_PASSWORD: 'n}iUs~SB[7Pmr}GO'
  DATABASE_SSL: 'true'
  DATABASE_CA_SECRET_NAME: 'projects/925437110000/secrets/prod-postgresql-cert'
  GCS_BUCKET_NAME: 'strapi-cms-gcs'
  GCS_BASE_PATH: 'uploads'
  ALGOLIA_ADMIN_KEY: '8d4877c470e54da264b55789dd4f0909'
  ALGOLIA_APP_ID: 'V1O1Y893BB'
  CSP_URLS_TRUSTED: 'loremflickr.com,storage.googleapis.com'

beta_settings:
  cloud_sql_instances: 'strapi-cms-441915:us-central1:strapi'